### ISSUE TITLE
Fails to load on some websites

### ISSUE THREAD

**Issue by xypnox** [Abdillah/hypothesis-firefox#9]
Ex: https://yerinalexey.srht.site/2021-05-01-Why-I-do-not-use-docker.html

The error from the console: `Content Security Policy: The page’s settings blocked the loading of a resource at https://cdn.hypothes.is/hypothesis/1.815.0/build/scripts/annotator.bundle.js?1a1dc7 (“default-src”).`

**Comment by Abdillah** [comment]
Oh, is there a possibility that the hypothes.is server has captcha security active?
Please try to access the URL (e.g. https://cdn.hypothes.is/hypothesis/1.815.0/build/scripts/annotator.bundle.js?1a1dc7) in a new tab and see if the captcha shown.

**Comment by Abdillah** [comment]
Ah I think this is due to the CSP alone, okay thanks for the report, I will try to investigate the CSP..

**Comment by xypnox** [comment]
Tested the new version out, it works nicely. 
Thanks a lot for fixing the bug!
